[package]
name = "stockr"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.33"
clap = { version = "4.4.18", features = ["derive"] }
tokio = { version = "1.36.0", features = ["full"] }
yahoo_finance_api = "2.1.0"
